/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "keelink-fabric-v2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(keemash_fabric_v2_Id128, keemash_fabric_v2_Id128, AUTO)


PB_BIND(keemash_fabric_v2_ResumeCursor, keemash_fabric_v2_ResumeCursor, AUTO)


PB_BIND(keemash_fabric_v2_Hello, keemash_fabric_v2_Hello, 2)


PB_BIND(keemash_fabric_v2_Welcome, keemash_fabric_v2_Welcome, AUTO)


PB_BIND(keemash_fabric_v2_NodeDescriptor, keemash_fabric_v2_NodeDescriptor, AUTO)


PB_BIND(keemash_fabric_v2_EndpointDescriptor, keemash_fabric_v2_EndpointDescriptor, AUTO)


PB_BIND(keemash_fabric_v2_GraphEdge, keemash_fabric_v2_GraphEdge, AUTO)


PB_BIND(keemash_fabric_v2_GraphSnapshot, keemash_fabric_v2_GraphSnapshot, 2)


PB_BIND(keemash_fabric_v2_ControlRequest, keemash_fabric_v2_ControlRequest, 2)


PB_BIND(keemash_fabric_v2_ControlResult, keemash_fabric_v2_ControlResult, AUTO)


PB_BIND(keemash_fabric_v2_TelemetrySample, keemash_fabric_v2_TelemetrySample, 2)


PB_BIND(keemash_fabric_v2_TaskEntry, keemash_fabric_v2_TaskEntry, AUTO)


PB_BIND(keemash_fabric_v2_TaskSnapshot, keemash_fabric_v2_TaskSnapshot, 2)


PB_BIND(keemash_fabric_v2_MemorySnapshot, keemash_fabric_v2_MemorySnapshot, AUTO)


PB_BIND(keemash_fabric_v2_LogLine, keemash_fabric_v2_LogLine, 2)


PB_BIND(keemash_fabric_v2_Gap, keemash_fabric_v2_Gap, AUTO)


PB_BIND(keemash_fabric_v2_Probe, keemash_fabric_v2_Probe, AUTO)


PB_BIND(keemash_fabric_v2_FirmwareBlockDescriptor, keemash_fabric_v2_FirmwareBlockDescriptor, AUTO)


PB_BIND(keemash_fabric_v2_FirmwareArtifactSignedFields, keemash_fabric_v2_FirmwareArtifactSignedFields, 2)


PB_BIND(keemash_fabric_v2_FirmwareArtifactManifest, keemash_fabric_v2_FirmwareArtifactManifest, 2)


PB_BIND(keemash_fabric_v2_OtaStageRequest, keemash_fabric_v2_OtaStageRequest, AUTO)


PB_BIND(keemash_fabric_v2_OtaStageChunk, keemash_fabric_v2_OtaStageChunk, 2)


PB_BIND(keemash_fabric_v2_OtaStageStatus, keemash_fabric_v2_OtaStageStatus, AUTO)


PB_BIND(keemash_fabric_v2_OtaDeployRequest, keemash_fabric_v2_OtaDeployRequest, AUTO)


PB_BIND(keemash_fabric_v2_OtaDeployStatus, keemash_fabric_v2_OtaDeployStatus, AUTO)


PB_BIND(keemash_fabric_v2_OtaCancelRequest, keemash_fabric_v2_OtaCancelRequest, AUTO)


PB_BIND(keemash_fabric_v2_OtaPrepare, keemash_fabric_v2_OtaPrepare, 2)


PB_BIND(keemash_fabric_v2_OtaBlockChunk, keemash_fabric_v2_OtaBlockChunk, 2)


PB_BIND(keemash_fabric_v2_OtaCommit, keemash_fabric_v2_OtaCommit, AUTO)


PB_BIND(keemash_fabric_v2_OtaAbort, keemash_fabric_v2_OtaAbort, AUTO)


PB_BIND(keemash_fabric_v2_OtaQuery, keemash_fabric_v2_OtaQuery, AUTO)


PB_BIND(keemash_fabric_v2_OtaTransferStatus, keemash_fabric_v2_OtaTransferStatus, AUTO)


PB_BIND(keemash_fabric_v2_OtaTransfer, keemash_fabric_v2_OtaTransfer, 2)


PB_BIND(keemash_fabric_v2_OtaBootReport, keemash_fabric_v2_OtaBootReport, AUTO)


PB_BIND(keemash_fabric_v2_Envelope, keemash_fabric_v2_Envelope, 2)























#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

